const gentleThoughts = [
    "Healing isn't a straight line, and having a heavy day doesn't erase all of your progress.",
    "Take a deep breath. You don't have to figure everything out right this second.",
    "You are doing the best you can with what you have, and that is completely enough.",
    "Be gentle with yourself. You are growing, even if it feels invisible right now.",
    "It is okay to rest. The world can wait while you take care of you.",
    "Your worth is not defined by your productivity. It is okay to just exist right now.",
    "Give yourself permission to take things one small moment at a time.",
    "You have survived 100% of your hardest days. Your resilience is quiet but incredibly powerful.",
    "It's completely okay if all you did today was breathe and get through it.",
    "You don't need to be perfect to be worthy of love, kindness, and belonging.",
    "Be proud of how hard you are trying, even on the days when it feels like nobody notices.",
    "Softness is a strength. Let yourself feel, let yourself rest, and let yourself heal.",
    "You are allowed to set boundaries. Protecting your peace is a beautiful form of self-care.",
    "The storm will pass, the sun will return, and you will find your footing again.",
    "You belong here, exactly as you are, with all your imperfections and beautiful progress.",
    "You don’t have to prove yourself to anyone. Just being here and trying is more than enough.",
    "Allow yourself the same grace and patience that you so freely give to others.",
    "It is okay to change your mind, redirect your steps, or start over entirely.",
    "Your energy is valuable. You are allowed to say 'no' to things that drain your peace.",
    "In a world that constantly tells you to hurry, there is deep courage in choosing to slow down.",
    "Even if today felt like a setback, tomorrow is a brand new canvas waiting for you.",
    "You are a whole person, not a project. You don't need to constantly 'fix' yourself to be worthy.",
    "Trust the timing of your life. Growth often happens in the quietest, most unseen spaces.",
    "Be proud of the quiet battles you've fought and won entirely on your own.",
    "You don’t have to carry the weight of the entire world on your shoulders. Put it down for a bit.",
    "Your feelings are valid, whatever they may be. Let yourself feel them without judgment.",
    "There is no timeline for your healing or success. Go at your own beautiful pace.",
    "You are far more resilient than you realize, and you are fully capable of getting through this.",
    "It is okay if your biggest achievement today was simply holding onto hope.",
    "No matter how dark the night gets, it can never stop the morning from arriving."
];
